import React from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { Source } from '../types';

interface PDFLayoutProps {
  country: string;
  topic: string;
  summary: string;
  sources: Source[];
  flagUrl: string | null;
}

const PDFLayout: React.FC<PDFLayoutProps> = ({ country, topic, summary, sources, flagUrl }) => {
  return (
    // A4 size: 210mm x 297mm. Add padding.
    // Using Tailwind CSS for styling the content within the PDF.
    <div className="p-8 bg-white text-black font-sans">
      <header className="flex items-center justify-between border-b-2 border-gray-300 pb-4 mb-6">
        <div>
          <h1 className="text-4xl font-bold text-gray-800">MUN Briefing: {country}</h1>
          <p className="text-lg text-gray-600 mt-2">Topic: {topic}</p>
        </div>
        {flagUrl && <img src={flagUrl} alt={`${country} flag`} className="w-32 h-auto object-contain border border-gray-200 shadow-md" />}
      </header>
      
      <main>
        <div className="prose max-w-none">
          <ReactMarkdown remarkPlugins={[remarkGfm]}>{summary}</ReactMarkdown>
        </div>

        {sources && sources.length > 0 && (
          <div className="mt-8 pt-4 border-t border-gray-300">
            <h3 className="text-xl font-semibold text-gray-800 mb-3">
              Sources
            </h3>
            <ul className="list-disc list-inside space-y-2">
              {sources.map((source, index) => (
                <li key={index}>
                  <a href={source.uri} target="_blank" rel="noopener noreferrer" className="text-blue-600 hover:underline break-all">
                    {source.title}
                  </a>
                </li>
              ))}
            </ul>
          </div>
        )}
      </main>

      <footer className="text-center text-xs text-gray-500 mt-8 pt-4 border-t border-gray-300">
        <p>Generated by MUN Assistant | Powered by Gemini 2.5 Pro</p>
      </footer>
    </div>
  );
};

export default PDFLayout;